spring:
  application:
    name: guli-third-party
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      oss:
        endpoint: oss-cn-chengdu.aliyuncs.com
      access-key: LTAI5tSi5iGjyGWG2HfCcjL1
      secret-key: WvHxunAPpv69UoqePjmqoBsPOIff37
server:
  port: 30000